# Generated by Django 2.2.5 on 2020-02-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20200227_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='subtitle',
            field=models.CharField(default='', max_length=80),
        ),
    ]
