# Generated by Django 2.2.5 on 2020-02-27 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roomtype_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='subtitle',
        ),
    ]
